# Generated by Django 4.2.13 on 2026-05-03 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promos', '0001_initial'),
        ('houses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('partially_paid', 'Предоплата внесена'), ('paid', 'Полностью оплачено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая цена')),
                ('prepayment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Предоплата (10%)')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Остаток')),
                ('applied_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)')),
                ('access_code', models.CharField(blank=True, max_length=10, verbose_name='Код доступа')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='Заехал')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='houses.house', verbose_name='Дом')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.promocode', verbose_name='Промокод')),
                ('selected_services', models.ManyToManyField(blank=True, to='houses.service', verbose_name='Выбранные услуги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
